apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 27.31.0 
    releaseName: prometheus
    valuesFile: configs/prometheus-config.yaml 
