grafana:
  enabled: false
alertmanager:
  enabled: false
prometheus:
  enabled: false

# Disable all sub-charts
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-operator:
  enabled: false
kubeDns:
  enabled: false

# Disable the creation of default rules and servicemonitors
defaultRules:
  create: false
  rules:
    alertmanager: false
    etcd: false
    general: false
    k8s: false
    kubeApiserver: false
    kubelet: false
    kubeScheduler: false
    kubeProxy: false
    node: false
    prometheus: false
    prometheusOperator: false
    kubeControllerManager: false
