apiVersion: v1
kind: Service
metadata:
  name: triton-service
  labels:
    app: triton-inference-server
spec:
  selector:
    app: triton-inference-server
  type: LoadBalancer
  ports:
    - name: http-triton
      port: 8000
      targetPort: 8000
      nodePort: 30800
      protocol: TCP
    - name: grpc-triton
      port: 8001
      targetPort: 8001
      nodePort: 30801
      protocol: TCP
    - name: metrics-triton
      port: 8002
      targetPort: 8002
      nodePort: 30802
      protocol: TCP
