apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 51.5.1
    releaseName: prometheus-stack-crds
    # By default, crds are enabled. We explicitly disable everything else.
    valuesContent: |
      grafana:
        enabled: false
      prometheus:
        enabled: false
      alertmanager:
        enabled: false
      kube-state-metrics:
        enabled: false
      prometheus-node-exporter:
        enabled: false
